// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/fake-select-data": {
    params: {};
  };
  "/api/docs/prefetch": {
    params: {};
  };
  "/api/docs/search": {
    params: {};
  };
  "/llms.txt": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/:section/:page": {
    params: {
      "section": string;
      "page": string;
    };
  };
  "/docs/:section/:page/og-image": {
    params: {
      "section": string;
      "page": string;
    };
  };
  "/test": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/fake-select-data" | "/api/docs/prefetch" | "/api/docs/search" | "/llms.txt" | "/docs" | "/docs/:section/:page" | "/docs/:section/:page/og-image" | "/test" | "/*";
  };
  "routes/api.fake-select-data.tsx": {
    id: "routes/api.fake-select-data";
    page: "/api/fake-select-data";
  };
  "routes/api.docs.prefetch.ts": {
    id: "routes/api.docs.prefetch";
    page: "/api/docs/prefetch";
  };
  "routes/api.docs.search.tsx": {
    id: "routes/api.docs.search";
    page: "/api/docs/search";
  };
  "routes/llms[.txt].ts": {
    id: "routes/llms[.txt]";
    page: "/llms.txt";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs" | "/docs/:section/:page" | "/docs/:section/:page/og-image";
  };
  "routes/docs.$section.$page.tsx": {
    id: "routes/docs.$section.$page";
    page: "/docs/:section/:page" | "/docs/:section/:page/og-image";
  };
  "routes/docs.$section.$page.og-image.tsx": {
    id: "routes/docs.$section.$page.og-image";
    page: "/docs/:section/:page/og-image";
  };
  "routes/docs._index.ts": {
    id: "routes/docs._index";
    page: "/docs";
  };
  "routes/test.tsx": {
    id: "routes/test";
    page: "/test";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};