// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/fake-select-data": {
    params: {};
  };
  "/api/docs/prefetch": {
    params: {};
  };
  "/api/docs/search": {
    params: {};
  };
  "/llms.txt": {
    params: {};
  };
  "/testing": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/:section/:page": {
    params: {
      "section": string;
      "page": string;
    };
  };
  "/docs/:section/:page/og-image": {
    params: {
      "section": string;
      "page": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/fake-select-data" | "/api/docs/prefetch" | "/api/docs/search" | "/llms.txt" | "/testing" | "/docs" | "/docs/:section/:page" | "/docs/:section/:page/og-image" | "/*";
  };
  "routes/api.fake-select-data.tsx": {
    id: "routes/api.fake-select-data";
    page: "/api/fake-select-data";
  };
  "routes/api.docs.prefetch.ts": {
    id: "routes/api.docs.prefetch";
    page: "/api/docs/prefetch";
  };
  "routes/api.docs.search.tsx": {
    id: "routes/api.docs.search";
    page: "/api/docs/search";
  };
  "routes/llms[.txt].ts": {
    id: "routes/llms[.txt]";
    page: "/llms.txt";
  };
  "routes/testing.tsx": {
    id: "routes/testing";
    page: "/testing";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs" | "/docs/:section/:page" | "/docs/:section/:page/og-image";
  };
  "routes/docs.$section.$page.tsx": {
    id: "routes/docs.$section.$page";
    page: "/docs/:section/:page" | "/docs/:section/:page/og-image";
  };
  "routes/docs.$section.$page.og-image.tsx": {
    id: "routes/docs.$section.$page.og-image";
    page: "/docs/:section/:page/og-image";
  };
  "routes/docs._index.ts": {
    id: "routes/docs._index";
    page: "/docs";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.fake-select-data": typeof import("./app/routes/api.fake-select-data.tsx");
  "routes/api.docs.prefetch": typeof import("./app/routes/api.docs.prefetch.ts");
  "routes/api.docs.search": typeof import("./app/routes/api.docs.search.tsx");
  "routes/llms[.txt]": typeof import("./app/routes/llms[.txt].ts");
  "routes/testing": typeof import("./app/routes/testing.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/docs.$section.$page": typeof import("./app/routes/docs.$section.$page.tsx");
  "routes/docs.$section.$page.og-image": typeof import("./app/routes/docs.$section.$page.og-image.tsx");
  "routes/docs._index": typeof import("./app/routes/docs._index.ts");
  "routes/$": typeof import("./app/routes/$.tsx");
};