import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DreamyProvider } from "@/components/dreamy-provider";
import { getColorModeHTMLProps, getSSRColorMode } from "@dreamy-ui/react/rsc";
import { cookies } from "next/headers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"]
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const colorMode = getSSRColorMode((await cookies()).toString());

    return (
        <html
            lang="en"
            {...getColorModeHTMLProps(colorMode)}
        >
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <DreamyProvider colorMode={colorMode}>{children}</DreamyProvider>
            </body>
        </html>
    );
}
